version: '3.1'

services:
  registry:
    image: localhost:5000/govrnanza.registry.webapi:dev
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - REGISTRY_DB_PASSWORD_SECRET_FILE=/run/secrets/registry_db_passwordV2
    ports:
      - "80:80"
    networks:
      - web
    secrets:
       - registry_db_passwordV2

secrets:
   registry_db_passwordV2:
     external: true

networks:
  web: